name: Clemson University Hadoop Cluster
highlighter: rouge
include: ['.htaccess']
exclude: ['README','deploy.sh','build.sh','Makefile','README.md']
baseurl: "/cypress-userguide" # the subpath of your site, e.g. /blog
